### ISSUE TITLE
Feature test appears to be broken

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/return-string-data-lab#10]
The feature test that tests the function of the more button in the index does not appear to work properly. The content on the page does not appear to update after the More Info button has been clicked by the test suite.

**Comment by lizbur10** [comment]
To fix this so the test suite will run, go to the products/index view and, in the javascript code, use var or const to declare the `id` variable instead of let

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
