### ISSUE TITLE
Seeds file should include product descriptions

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/return-string-data-lab#11]
The seeds file does not include any product descriptions, which makes it difficult to verify that the "More Info" button for products works correctly.

I would recommend using `Faker::Lorem` (or similar) to generate fake descriptions for each product in the seeds file.

Reported by @nicoleeidi.

**Comment by stefclaus** [comment]
Great recommendation, Ian. I would add that you need to pass in a key value pair to make faker work. I would suggest adding a line like this in your test:

`  Product.create(:name => products.sample, :price => Faker::Number.between(from: 1, to: 1500), :description => Faker::Lorem.sentence(word_count: 3, supplemental: true, random_words_to_add: 4).chop)`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
