### ISSUE TITLE
Rails Gem Update

### ISSUE THREAD

**Issue by dwyn** [learn-co-curriculum/return-string-data-lab#13]
This app was forked with `gem 'rails', '4.2.5'` but with that gem there are a few deprecated dependencies  - Errors are thrown when running rspec. Upgrading to `gem 'rails', '4.2.8'` seems to have solved the problem. 

This isn't the first lab I've run into this issue is there any feedback on what is causing the hiccup?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
