### ISSUE TITLE
No static controller built out for this lab (config/routes.rb)

### ISSUE THREAD

**Issue by JulJen** [learn-co-curriculum/return-string-data-lab#15]
Rails.application.routes.draw do

  # there is no static controller,  comment out or remove it altogether?
  # get 'home', to: 'static#home'

  resources :orders
  resources :invoices
  resources :products

  get 'products/:id/description' => 'products#description'
  get 'products/:id/inventory' => 'products#inventory'
end

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
