### ISSUE TITLE
Requirement for number 6 in the lab 

### ISSUE THREAD

**Issue by jmulloy** [learn-co-curriculum/return-string-data-lab#16]
The #6 in the lab is straightforward when reading the lab at first. However, after getting started on it (especially compared to the previous lesson), I would separate the requirements for that one test into separate tests. The test is looking for perfect code for inventory and description that have different pieces of functionality in the application. If they were separate a student could work on description and get that passing then move on to work on displaying the inventory messages based on the count set up in the inventory method. Having the 2 pieces of functionality tied to the same test was resulting in looking for an issue with code that was working fine but the error was misleading.

Thanks!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
