### ISSUE TITLE
test passed using only var

### ISSUE THREAD

**Issue by SallyZ12** [learn-co-curriculum/return-string-data-lab#17]
in the view/products/index.html.erb file, the code only passed the test using var not let. Shouldn't let be used rather than var?

**Comment by SallyZ12** [comment]
Also, found that const works to pass the tests.  So, we are down to const works and var works, but not let.

**Comment by SallyZ12** [comment]
oops, didn't mean to hit close button.

**Comment by SallyZ12** [comment]
see prior comment on const and var.

**Comment by Marie-Burns22** [comment]
I also had this issue today.  The app  works in the browser using `let` for the logic to append information when `More info` is clicked.  However, it would not pass `product_feature_spec.rb:8` until `let` was changed to `var` in my code.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
