### ISSUE TITLE
all test passed without coding solution

### ISSUE THREAD

**Issue by SaraGinsburg** [learn-co-curriculum/return-string-data-lab#18]
all tests passed, even before I started coding my solution.

**Comment by SaraGinsburg** [comment]
was resolved after updating rails gem to gem 'rails', '4.2.8'

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
