### ISSUE TITLE
Faker::Number.between accepts key value arguments

### ISSUE THREAD

**Issue by Saturn226** [learn-co-curriculum/return-string-data-lab#20]
As of v2.0, Faker::Number.between accepts key value arguments that currently breaks the test.

spec/views/invoices_index_view_spec.rb line: 11
spec/views/ orders_index_view_spec.rb line: 10

Need to be updated to

      Product.create(:name => products.sample, :price => Faker::Number.between(from: 1, to: 1500))

**Comment by stefclaus** [comment]
I would echo what Ashley says above but point out that this needs to be changed both in the seeds file and (seeds.rb) and in spec/views/invoices_index_view_spec.rb.

**Comment by stefclaus** [comment]
Also you'll need to change it here: 

spec/views/orders_index_view_spec.rb

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
