### ISSUE TITLE
Issues with schema, tests, and seeds

### ISSUE THREAD

**Issue by stefclaus** [learn-co-curriculum/return-string-data-lab#21]
It's not you. This lab has a ton of issues not at all related to the curriculum.  It's frustrating, but let me try to save you some pain.

Most of them are covered below, but here's what I wish I had known when I started:

-You're going to need to create inventory and description fields in your product schema. Go ahead and do that. (Weirdly, this isn't in the solution--no idea how it is supposed to work without those tho!)

- You'll need to make the change Ashely suggests below in three different places--in your seeds, and in both files in your view spec. (In short, you need to add the to and from keys for Faker::Number like so: `Faker::Number.between(from: 1,to: 1500)`

-No seeds for inventory or description are included. It's very hard to test out what you are doing without it! I'd recommend writing the following seed:
`  Product.create(:name => products.sample, :price => Faker::Number.between(from: 1, to: 100), :description => Faker::Lorem.sentence(word_count: 3, supplemental: true, random_words_to_add: 4).chop, :inventory => Faker::Number.between(from: 1, to: 20))
` 

Good luck!

**Comment by blainelawson** [comment]
`You'll need to make the change Ashely suggests below in three different places--in your seeds, and in both files in your view spec. (In short, you need to add the to and from keys for Faker::Number like so: Faker::Number.between(from: 1,to: 1500)`

Worked perfectly, thanks!

**Comment by ermarie** [comment]
The 'Faker::Lorem.sentence(word_count: 3, supplemental: true, random_words_to_add: 4)' part did not work for me. I just set description equal to `"This is a test description with more text than should be there."`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
