### ISSUE TITLE
Selenium webdriver not working; causing tests to fail

### ISSUE THREAD

**Issue by cassaram09** [learn-co-curriculum/return-string-data-lab#3]
A student passed all the tests in this lab, but when running the test suite (in the IDE), it would freeze up on the ProductsController / Products Index test section, and then spit out an error about requiring the Gecko driver for FireFox:

```
Selenium::WebDriver::Error::WebDriverError:                                                                                                                                           
Unable to find Mozilla geckodriver. Please download the server from https://github.com/mozilla/geckodriver/releases and place it somewhere on your PATH. 
More info at https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver.
``` 

Also got a similar Selenium error when running the solution branch, about port 7504 being locked up. The test would timeout after 45 seconds:

```
Selenium::WebDriver::Error::WebDriverError:                                                                                                                                           
       unable to bind to locking port 7054 within 45 seconds  
```

The student had one failing test.

Adding the poltergeist gem seemed to fix this.

`gem 'poltergeist'`

And add this to the `spec/rails_helper.rb file`:
``` 
require 'capybara/poltergeist'
Capybara.javascript_driver = :poltergeist
```

After making the changed all of the student's tests passed .

**Comment by DakotaLMartinez** [comment]
When fixing this issue locally, we also had to run `npm install -g phantomjs` so that Poltergeist would have access to phantomjs.
