### ISSUE TITLE
    Selenium::WebDriver::Error::WebDriverError:

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/return-string-data-lab#4]
ERROR: 
   Selenium::WebDriver::Error::WebDriverError:
       unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)
I have Firefox installed, working and updated.
I have all but 1 test passing and consistently get the above error. 
I have tried to update Selenium Web Driver, but it says "nothing to update".
I have tried running the tests with the 'Solution' code, and it produces the same error 
I have tried "gem update selenium-webdriver", no change, same error. 

Finally, I have tried to run the tests by commenting out the one below, no change, same error. 
...../spec/features/product_feature_spec.rb

require 'rails_helper'

RSpec.describe "Product Index", type: :feature do
  before do
    Product.destroy_all
  end

  # it 'gets the description and inventory', js: true do
  #   product = Product.create!(name: "Test Product", inventory: 0, description: "This is a test description with more text than should be there.")
  #   visit products_path
  #   expect(page).to have_content product.name
  #   expect(page).not_to have_content product.description
  #   click_button "More Info"
  #   expect(page).to have_content product.description
  #   expect(page).to have_content "Sold Out"
  #   product.inventory = 1
  #   product.save
  #   visit products_path
  #   click_button "More Info"
  #   expect(page).to have_content "Available"
  # end
end

**Comment by gj** [comment]
Fixed by #7.

Thanks @smithWEBtek !
