### ISSUE TITLE
Tests in Product Feature Spec do not recognize jQuery

### ISSUE THREAD

**Issue by jmstrick93** [learn-co-curriculum/return-string-data-lab#9]
In my opinion, this test should either be repaired or, if that is not possible, the lab should specify in the instructions that jQuery is not to be used here.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #28. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
